language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install -y redis-server
env:
  global:
    - ALCOTEST_SHOW_ERRORS=1
    - PINS="irmin.dev:--dev irmin-mem.dev:--dev irmin-fs.dev:--dev irmin-http.dev:--dev irmin-git.dev:--dev irmin-unix.dev:--dev irmin-test.dev:https://github.com/mirage/irmin.git irmin-chunk.dev:--dev git.dev:--dev git git-unix.dev:--dev  git-http.dev:--dev digestif.dev:--dev irmin-redis.dev:."
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="irmin-redis.dev" TESTS=true
    - OCAML_VERSION=4.07 PACKAGE="irmin-redis.dev" TESTS=true
